config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  
  get 'books/search'

  root 'static_pages#top'
  get '/signup', to: 'users#new'
  
   # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :events
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events
  
  before_save { self.email = email.downcase }

  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true    
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
   include SessionsHelper
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    
  
  def search
     itemName = params[:serect]
     URI.encode_www_form({itemName: serect})
     uri = parse("https://app.rakuten.co.jp/services/api/IchibaItem/Search/20170706?[itemName]=[]…")
     response = NET::HTTP>get.response(uri)
     result = JSON.parse(response.bady)
     @itemName = resul ["results"][0][itemName]
    end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    def create
        event = Event.new(event_params)
        event.save!
        @events = Event.where(user_id: current_user.id)
    end

    def update
        event = Event.find(params[:id])
        @events = Event.where(user_id: current_user.id)
        event.update(event_params)
    end

    def destroy
        @user = User.find(params[:id])
        event = Event.find(params[:id])
        event.destroy
        redirect_to user_path(@user)
    end

    private
    def event_params
        params.require(:event).permit(:title, :start, :end, :user_id, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = '認証に失敗しました。'
      render :new
    end
  end

  def destroy
    log_out
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.paginate(page: params[:page])
  end
  
  def show
    @user = User.find(params[:id])
    @events = Event.where(user_id: @user.id)
    @event = Event.new
  end

  def new
    @user = User.new
  end

  def create
  @user = User.new(user_params)
  if @user.save
    log_in @user # 保存成功後、ログインします。
    flash[:success] = '新規作成に成功しました。'
    redirect_to @user
  else
    render :new
  end
end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_name = "")
    base_title = "AttendanceApp"
    if page_name.empty?
      base_title
    else
      page_name + " | " + base_title
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # 引数に渡されたユーザーオブジェクトでログインします。
  def log_in(user)
    session[:user_id] = user.id
  end

  # セッションと@current_userを破棄します
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # 現在ログイン中のユーザーがいる場合オブジェクトを返します。
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # 現在ログイン中のユーザーがいればtrue、そうでなければfalseを返します。
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/search.html.erb
     <%= form_tag books_search_path, method: :get do  %>
        <%= label_tag :keyword, 'キーワード検索' %>
        <%= text_field_tag 'keyword', params[:keyword] %>
        <%= submit_tag "検索" %>
<% end %>
    <table>
     <thead>
      <tr>
       <th>商品名</th>
       <th>価格</th>
       
      </tr>
     </thead>
      <tbody>
      
       <% if @books.present? %>
        <% @books.each do |book| %>
       
        <tr>
            <td><%= link_to book.title, "#{book.title}" %></td>
            
          
        </tr>
      
       <% end %>
      </tbody>
     </table>
      <% end %>
      

app/views/events/_edit.html.erb
<% events.each do |event| %>
    <div id='inputScheduleEditForm<%= event.id %>' class="modal fade" tabindex="-1">
        <div class="modal-dialog modal-nm">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">スケジュール編集</h4>
                </div>
                <div class="modal-body">
                    <div  class="col">
                        <%= form_with(model: event, url: users_event_path(event), method: :put) do |f| %>
                            <p>
                                <span>タイトル</span>
                                <span id="inputTitle" value=""><%= f.text_field :title, class: "form-control", placeholder: "タイトルを入力してください" %></span>
                            </p>
                            <span>開始日時</span>
                            <span><%= f.datetime_field  :start, placeholder: "XXXX-XX-XX", class:"field" %> ~ </span><br>
                            <span>終了日時</span>
                            <span><%= f.datetime_field  :end, placeholder: "XXXX-XX-XX", class:"field" %></span>
                            <span><br>
                                詳細
                                <%= f.text_field :body, class: "form-control", placeholder: "タイトルの詳細を記入してください" %>
                            </span>
                            <div class="modal-footer">
                                <%= f.hidden_field :user_id, :value => current_user.id %>
                                <%= f.submit "編集する", class: "btn btn-primary" %>
                                <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Attendance App", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Top", root_path %></li>
        <li><%= link_to "Log in", login_path %></li>
        <li><%= link_to "search", books_search_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  
  <head>
    <title><%= full_title(yield(:title)) %></title>
    ~
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/core/main.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/daygrid/main.min.css">
~
    
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    
    <div class="container">
      <%= form_with url: books_search_path, local: true do |f|%>
      <%= f.text_field :serect, class: "form-control" %>
      <% end %>
      <% flash.each do |message_type, msg| %>
        <div class="alert alert-<%= message_type %>"><%= msg %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/top.html.erb
<% provide(:title, "Top") %>

<div class="type-mask">
<h2>サンプルテキスト</h2>
</div>

<P>
    <img src="download.jpg"  class="colorfilter-image2">
</p>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>

<% if params[:name].present? %>
　<h1>検索結果</h1>
<% else %>
　<h1>ユーザー一覧</h1>
<% end %>

<div class="col-md-10 col-md-offset-1">
  <%= will_paginate %>

<div align="right">
  <%= form_tag( users_path, method: "get") do %>
    <% label_tag :name %><%= text_field_tag :name, params[:name] %>
      <%= submit_tag "ユーザー名検索",class: "btn btn-success"  %>
    <% end %>
    </div>

  <table class="table table-condensed table-hover" id="table-users">
    <thead>

      <tr>
        <th><%= User.human_attribute_name :name %></th>
        <th></th>
      </tr>
    </thead>
    
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
        <td>
          <% if current_user.admin? && !current_user?(user) %>
            <%= link_to "削除", user, method: :delete,
                data: { confirm: "削除してよろしいですか？" },
                class: "btn btn-danger" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>ユーザー登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f| %>
    <%= render 'shared/error_messages' %>
      <%= f.label :name, class: "label-signup" %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :email, class: "label-signup" %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :password, class: "label-signup" %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, "Confirmation", class: "label-signup" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit "新規作成", class: "btn btn-primary btn-block btn-signup" %>
    <% end %>
  </div>

app/views/users/show.html.erb
<h3 class="text-center">カレンダー</h3>
<!-- カレンダーの表示 -->
<div id="calendar"></div>
<!-- もしユーザーがログインしていたら -->
<% if logged_in? %>
    <!-- ページのparams.idがログインユーザー.idと同じなら -->
    <% if @user.id == current_user.id %>
        <div id="inputScheduleForm" class="modal fade" tabindex="-1">
            <div class="modal-dialog modal-nm">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">スケジュール登録</h4>
                    </div>
                    <div class="modal-body">
                        <%= form_with model: @events, url: events_path do |f| %>
                            <div  class="col">
                                    <p>
                                        <span>タイトル</span>
                                        <span><%= f.text_field :title, class: "form-control", placeholder: "タイトルを入力してください" %></span>
                                    </p>
                                    <span>開始日時</span>
                                    <span><%= f.datetime_field  :start, placeholder: "XXXX-XX-XX", class:"field" %> ~ </span><br>
                                    <span>終了日時</span>
                                    <span><%= f.datetime_field :end, placeholder: "XXXX-XX-XX", class:"field" %></span><br>
                                    <span>詳細
                                    <%= f.text_field :body, class: "form-control", placeholder: "タイトルの詳細を記入してください" %></span>
                            </div>
                            <div class="modal-footer">
                                <%= f.submit "登録する", class: "btn btn-primary" %>
                                <%= f.hidden_field :user_id, :value => current_user.id %>
                                <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
<!-- 編集 ------------------------------------------------------------------>
        <div id="inputEditForm">
            <%= render 'events/edit', events: @events %>
        </div>
    <% end %>
<% end %>
    <script>
    // CRUDを行う際にCSRF対策のtokenを発行
        $(document).ready(function() {
        var prepare = function(options, originalOptions, jqXHR) {
          var token;
          if (!options.crossDomain) {
            token = $('meta[name="csrf-token"]').attr('content');
            if (token) {
              return jqXHR.setRequestHeader('X-CSRF-Token', token);
            }
          }
        };
        }
        )

        // カレンダー表示
        $('#calendar').fullCalendar ({
            header: {
                left: 'prev,next today',
                center: 'month,agendaWeek,agendaDay',
                right: 'title'
            },

            buttonText: {
                  prev: "<",
                  next: ">"
            },

            timezone: 'UTC',
            events: '/users/events.json',
            navLinks: true,
            selectable: true,
            selectHelper: true,
            // 日付クリック
            dayClick : function ( date , jsEvent , view ) {
                $('#inputScheduleForm').modal('show');
                },

            // event クリックで編集、削除
            eventClick : function(event, jsEvent , view) {
                jsEvent.preventDefault();
                $(`#inputScheduleEditForm${event.id}`).modal('show');
            },

            eventMouseover : function(event, jsEvent , view) {
                jsEvent.preventDefault();
            }
        })

    </script>